### ISSUE TITLE
Setting Up

### ISSUE THREAD

**Issue by Dev-Dipesh** [TheRusstler/Vehicle-Analysis#1]
Hey, I love the project you have built and want to give it a shot. I have read the whole report and already ordered parts specified, however, I appreciate a lot if you can give a few steps for how I can import this in Processing IDE.

Can you please provide a quick step by step instructions for setting up the project?

**Comment by Dev-Dipesh** [comment]
Okay seems like I get it working, I had to change few functions and `int` to `Integer` for casting errors.

Still if possible please provide some steps, to make sure I'm not missing anything.

![screen shot 2017-03-21 at 3 55 29 pm](https://cloud.githubusercontent.com/assets/3931017/24174637/edd31642-0e4e-11e7-8e24-14db85d1151c.png)

**Comment by TheRusstler** [comment]
Hi @Dev-Dipesh thanks for your interest!

Glad to see you have gotten it working. 
I just checked and it builds for me in Processing 3.3.

To open the project you need to open the file named "SerialDuplexCar" in Processing3 IDE.
The root directory must be named "SerialDuplexCar" also.

Line 14 in this file:

`boolean isUITest = true;`

Allows you to run the software with dummy data generated at random (hence the crazy graphs you see). Set this value to false & it will try to connect to the real device at the USB port defined on line 17:

`String port = "/dev/tty.usbserial-AI02KH63";`

You will need to change this value to match the correct port on your machine.

On OS X you can list the ports in terminal:

`ls /dev/tty.*`

I would advise you to start by connecting directly in the command line to ensure successful hardware configuration / connection / identify correct port.

On OS X you can use the built in terminal program [screen](http://serverfault.com/questions/81544/hidden-features-of-screen/81548#81548)

Perhaps this guide is a good starting point [https://learn.sparkfun.com/tutorials/obd-ii-uart-hookup-guide#first-communcation](https://learn.sparkfun.com/tutorials/obd-ii-uart-hookup-guide#first-communcation)

If you have any improvements / fixes, feel free to submit a pull request.

Happy to help :)

**Comment by Dev-Dipesh** [comment]
Thanks a lot @TheRusstler! Can't wait to test with real data.
